/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadorainterfaz;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author ianhe
 */
public class Calculadora extends JFrame {

    private JTextField txtNumero1;
    private JTextField txtNumero2;
    private JTextField txtResultado;
    private JComboBox<String> cmbOperacion;

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {
        JLabel lblNumero1 = new JLabel("Número 1:");
        txtNumero1 = new JTextField(10);

        JLabel lblOperacion = new JLabel("Operación:");
        String[] operaciones = { "Suma", "Resta", "Multiplicación", "División" };
        cmbOperacion = new JComboBox<>(operaciones);

        JLabel lblNumero2 = new JLabel("Número 2:");
        txtNumero2 = new JTextField(10);

        JButton btnCalcular = new JButton("Calcular");
        btnCalcular.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                calcular();
            }
        });

        JButton btnBorrar = new JButton("Borrar");
        btnBorrar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                txtNumero1.setText("");
                txtNumero2.setText("");
                txtResultado.setText("");
            }
        });

        JButton btnCerrar = new JButton("Cerrar");
        btnCerrar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });

        JLabel lblResultado = new JLabel("Resultado:");
        txtResultado = new JTextField(10);
        txtResultado.setEditable(false);

        // Configuración del layout
        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(5, 2));

        panel.add(lblNumero1);
        panel.add(txtNumero1);
        panel.add(lblOperacion);
        panel.add(cmbOperacion);
        panel.add(lblNumero2);
        panel.add(txtNumero2);
        panel.add(lblResultado);
        panel.add(txtResultado);

        // Panel para los botones
        JPanel panelBotones = new JPanel();
        panelBotones.setLayout(new FlowLayout(FlowLayout.CENTER, 10, 0));
        panelBotones.add(btnCalcular);
        panelBotones.add(btnBorrar);
        panelBotones.add(btnCerrar);

        // Agregar panel de botones al panel principal
        panel.add(new JLabel()); // Espacio vacío para alinear
        panel.add(panelBotones);

        add(panel);

        // Configuración del frame
        setSize(300, 200);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
    }

    private void calcular() {
        try {
            double numero1 = Double.parseDouble(txtNumero1.getText());
            double numero2 = Double.parseDouble(txtNumero2.getText());
            double resultado = 0;

            switch (cmbOperacion.getSelectedIndex()) {
                case 0:
                    resultado = numero1 + numero2;
                    break;
                case 1:
                    resultado = numero1 - numero2;
                    break;
                case 2:
                    resultado = numero1 * numero2;
                    break;
                case 3:
                    if (numero2 != 0) {
                        resultado = numero1 / numero2;
                    } else {
                        JOptionPane.showMessageDialog(this, "No se puede dividir por cero");
                        return;
                    }
                    break;
            }

            txtResultado.setText(String.valueOf(resultado));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese números válidos");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        new Calculadora();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
